### ISSUE TITLE
Implicit decay of array into pointer (clang-tidy error)

### ISSUE THREAD

**Issue by andrewkcorcoran** [morganstanley/binlog#43]
The [`BINLOG_CREATE_SOURCE_AND_EVENT`](https://github.com/Morgan-Stanley/binlog/blob/0c86ccdd2fe30b7ea16b2f73a3cad7083ba4c3a9/include/binlog/create_source_and_event.hpp#L38) macro does two implicit array to pointer conversions (`__FILE__` & `binlog::detail::concatenated_tags(__VA_ARGS__).data()`). Since this is a macro, it gets included in user code and users running clang-tidy on only their user code (and not on binlog itself) will receive errors.

**Comment by erenon** [comment]
Thanks for reporting! This particular warning (cppcoreguidelines-pro-bounds-array-to-pointer-decay) is disabled in the .clang-tidy config of binlog, as I couldn't see the use of it.

However, point is taken regarding tidy warning in a macro appearing in user code. This particular one will be fixed "by accident", when the [TODO on line 36](https://github.com/Morgan-Stanley/binlog/blob/0c86ccdd2fe30b7ea16b2f73a3cad7083ba4c3a9/include/binlog/create_source_and_event.hpp#L36) is fixed, and string_views will be constructed instead of strings.

**Comment by andrewkcorcoran** [comment]
Any change of getting this quickly fixed in the mean time while waiting on the larger todo?

**Comment by erenon** [comment]
You mean a year pondering on this should have been enough? See #127 .
